
import type { Property, User, Review, Booking } from "./types";
import placeholderImages from './placeholder-images.json';

const findImage = (id: string) => placeholderImages.placeholderImages.find(p => p.id === id)?.imageUrl || '';

export const users: User[] = [
  { id: 'user-1', name: 'Alice Johnson', email: 'alice.j@example.com', avatar: findImage('user-1') },
  { id: 'user-2', name: 'Bob Williams', email: 'bob.w@example.com', avatar: findImage('user-2') },
  { id: 'user-3', name: 'Charlie Brown', email: 'charlie.b@example.com', avatar: findImage('user-3') },
  { id: 'user-4', name: 'Diana Miller', email: 'diana.m@example.com', avatar: findImage('user-4') },
];

export const properties: Property[] = [
  {
    id: 'prop-1',
    name: 'Modern Villa with Ocean View',
    location: 'Monrovia, Liberia',
    pricePerNight: 850,
    weekendPrice: 950,
    weeklyDiscount: 15,
    description: 'Experience luxury in this stunning modern villa. With breathtaking ocean views, a private pool, and state-of-the-art amenities, it is the perfect getaway for families or groups of friends.',
    longStay: true,
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 8,
    amenities: ['Private Pool', 'WiFi', 'Kitchen', 'Air Conditioning', 'Free Parking', 'Ocean View', 'Gym', 'Hot Tub'],
    extras: [
        { name: 'Airport Pickup', price: 75, type: 'per_stay' },
        { name: 'Private Chef', price: 300, type: 'per_night' },
    ],
    rating: 4.9,
    reviewCount: 78,
    viewCount: 1250,
    images: [findImage('prop1-1'), findImage('prop1-2'), findImage('prop3-2')],
    owner: { id: users[0].id, name: users[0].name, avatar: users[0].avatar },
    propertyType: 'Villa',
    petFriendly: false,
    status: 'approved',
  },
  {
    id: 'prop-2',
    name: 'Cozy Downtown Apartment',
    location: 'Paynesville, Liberia',
    pricePerNight: 250,
    weekendPrice: 275,
    description: 'A charming and cozy apartment in the heart of the city. Perfect for solo travelers or couples looking to explore. Walking distance to major attractions.',
    longStay: false,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ['WiFi', 'Kitchen', 'Air Conditioning', 'Elevator'],
    extras: [
        { name: 'Daily Breakfast', price: 20, type: 'per_person' },
        { name: 'Cleaning Fee', price: 50, type: 'per_stay'},
    ],
    rating: 4.7,
    reviewCount: 124,
    viewCount: 2345,
    images: [findImage('prop2-1'), findImage('prop2-2')],
    owner: { id: users[1].id, name: users[1].name, avatar: users[1].avatar },
    propertyType: 'Apartment',
    petFriendly: true,
    status: 'approved',
  },
  {
    id: 'prop-3',
    name: 'Spacious Suburban Family Home',
    location: 'Ganta, Liberia',
    pricePerNight: 400,
    weeklyDiscount: 10,
    description: 'A beautiful and spacious home in a quiet suburban neighborhood. Features a large backyard with a grill, perfect for family gatherings. Close to parks and local eateries.',
    longStay: true,
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    amenities: ['WiFi', 'Kitchen', 'Free Parking', 'Backyard', 'Grill'],
    rating: 4.8,
    reviewCount: 56,
    viewCount: 980,
    images: [findImage('prop3-1'), findImage('prop3-2'), findImage('prop1-2')],
    owner: { id: users[2].id, name: users[2].name, avatar: users[2].avatar },
    propertyType: 'House',
    petFriendly: true,
    status: 'approved',
  },
  {
    id: 'prop-4',
    name: 'Luxury Penthouse with Cityscape',
    location: 'Buchanan, Liberia',
    pricePerNight: 1200,
    weekendPrice: 1500,
    description: 'Indulge in the ultimate urban luxury. This penthouse offers panoramic city views, a private rooftop terrace, and exquisite modern design. An unforgettable experience.',
    longStay: false,
    bedrooms: 2,
    bathrooms: 3,
    maxGuests: 4,
    amenities: ['Rooftop Terrace', 'WiFi', 'Kitchen', 'Air Conditioning', 'Gym', 'City View'],
    rating: 5.0,
    reviewCount: 32,
    viewCount: 1500,
    images: [findImage('prop4-1'), findImage('prop4-2')],
    owner: { id: users[0].id, name: users[0].name, avatar: users[0].avatar },
    propertyType: 'Condo',
    petFriendly: false,
    status: 'pending',
  },
  {
    id: 'prop-5',
    name: 'Charming Beachfront Bungalow',
    location: 'Harper, Liberia',
    pricePerNight: 600,
    weekendPrice: 700,
    weeklyDiscount: 5,
    description: 'Wake up to the sound of waves in this charming bungalow right on the beach. Direct beach access and stunning sunsets await you. Ideal for a romantic escape.',
    longStay: false,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ['Beach Access', 'WiFi', 'Kitchen', 'Air Conditioning', 'Patio'],
    extras: [
        { name: 'Romantic Package', price: 150, type: 'per_stay' }
    ],
    rating: 4.9,
    reviewCount: 91,
    viewCount: 1890,
    images: [findImage('prop5-1'), findImage('prop5-2')],
    owner: { id: users[3].id, name: users[3].name, avatar: users[3].avatar },
    propertyType: 'House',
    petFriendly: true,
    status: 'approved',
  },
  {
    id: 'prop-6',
    name: 'Rustic Countryside Cottage',
    location: 'Voinjama, Liberia',
    pricePerNight: 220,
    description: 'Escape to the peace and quiet of the countryside. This rustic cottage is surrounded by nature, offering a tranquil retreat with hiking trails and scenic beauty.',
    longStay: true,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 4,
    amenities: ['WiFi', 'Kitchen', 'Indoor Fireplace', 'Garden'],
    rating: 4.8,
    reviewCount: 65,
    viewCount: 750,
    images: [findImage('prop6-1'), findImage('prop6-2')],
    owner: { id: users[1].id, name: users[1].name, avatar: users[1].avatar },
    propertyType: 'House',
    petFriendly: false,
    status: 'rejected',
  },
  {
    id: 'prop-7',
    name: 'City Center Studio',
    location: 'Kakata, Liberia',
    pricePerNight: 180,
    description: 'A compact and modern studio in the bustling center of Kakata. Ideal for business travelers or solo adventurers.',
    longStay: false,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ['WiFi', 'Kitchenette', 'Air Conditioning'],
    rating: 4.5,
    reviewCount: 88,
    viewCount: 1100,
    images: [findImage('prop7-1'), findImage('prop7-2')],
    owner: { id: users[2].id, name: users[2].name, avatar: users[2].avatar },
    propertyType: 'Apartment',
    petFriendly: false,
    status: 'approved',
  },
  {
    id: 'prop-8',
    name: 'Riverside Cabin Retreat',
    location: 'Greenville, Liberia',
    pricePerNight: 350,
    weekendPrice: 400,
    description: 'A peaceful cabin located by the Sinoe River. Enjoy fishing, kayaking, and relaxing in nature.',
    longStay: true,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 5,
    amenities: ['River View', 'WiFi', 'Kitchen', 'Bonfire Pit'],
    rating: 4.9,
    reviewCount: 45,
    viewCount: 950,
    images: [findImage('prop8-1'), findImage('prop8-2')],
    owner: { id: users[3].id, name: users[3].name, avatar: users[3].avatar },
    propertyType: 'House',
    petFriendly: true,
    status: 'approved',
  },
  {
    id: 'prop-9',
    name: 'Gbarnga Garden Flat',
    location: 'Gbarnga, Liberia',
    pricePerNight: 280,
    description: 'A lovely ground-floor flat with a private garden. A green oasis in the city.',
    longStay: true,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ['Garden', 'WiFi', 'Kitchen', 'Free Parking'],
    rating: 4.7,
    reviewCount: 72,
    viewCount: 1300,
    images: [findImage('prop9-1'), findImage('prop9-2')],
    owner: { id: users[0].id, name: users[0].name, avatar: users[0].avatar },
    propertyType: 'Apartment',
    petFriendly: true,
    status: 'pending',
  },
  {
    id: 'prop-10',
    name: 'Zwedru Forest Lodge',
    location: 'Zwedru, Liberia',
    pricePerNight: 450,
    description: 'A unique lodge on the edge of the forest. Perfect for nature lovers and bird watchers.',
    longStay: false,
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    amenities: ['WiFi', 'Kitchen', 'Hiking Trails', 'Air Conditioning'],
    rating: 4.8,
    reviewCount: 55,
    viewCount: 880,
    images: [findImage('prop10-1'), findImage('prop10-2')],
    owner: { id: users[1].id, name: users[1].name, avatar: users[1].avatar },
    propertyType: 'House',
    petFriendly: false,
    status: 'approved',
  },
  {
    id: 'prop-11',
    name: 'Tubmanburg Townhouse',
    location: 'Tubmanburg, Liberia',
    pricePerNight: 320,
    weeklyDiscount: 5,
    description: 'A modern townhouse with all the comforts of home. Located in a friendly community.',
    longStay: true,
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 7,
    amenities: ['WiFi', 'Kitchen', 'Free Parking', 'Air Conditioning'],
    rating: 4.6,
    reviewCount: 61,
    viewCount: 1020,
    images: [findImage('prop11-1'), findImage('prop11-2')],
    owner: { id: users[2].id, name: users[2].name, avatar: users[2].avatar },
    propertyType: 'House',
    petFriendly: true,
    status: 'approved',
  },
  {
    id: 'prop-12',
    name: 'Harbel Plantation Villa',
    location: 'Harbel, Liberia',
    pricePerNight: 950,
    description: 'A luxurious villa on a historic rubber plantation. Offers a unique blend of history and modern comfort.',
    longStay: false,
    bedrooms: 5,
    bathrooms: 5,
    maxGuests: 10,
    amenities: ['Private Pool', 'WiFi', 'Kitchen', 'Air Conditioning', 'Gym'],
    rating: 4.9,
    reviewCount: 49,
    viewCount: 1700,
    images: [findImage('prop12-1'), findImage('prop12-2')],
    owner: { id: users[3].id, name: users[3].name, avatar: users[3].avatar },
    propertyType: 'Villa',
    petFriendly: false,
    status: 'approved',
  },
  {
    id: 'prop-13',
    name: 'Robertsport Surf Shack',
    location: 'Robertsport, Liberia',
    pricePerNight: 200,
    weekendPrice: 250,
    description: 'A simple, rustic shack perfect for surfers. Just steps away from Liberia\'s best waves.',
    longStay: false,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ['Beach Access', 'Kitchenette', 'Fan'],
    rating: 4.4,
    reviewCount: 150,
    viewCount: 2500,
    images: [findImage('prop13-1'), findImage('prop13-2')],
    owner: { id: users[0].id, name: users[0].name, avatar: users[0].avatar },
    propertyType: 'House',
    petFriendly: true,
    status: 'approved',
  },
  {
    id: 'prop-14',
    name: 'Sanniquellie Mountain Cabin',
    location: 'Sanniquellie, Liberia',
    pricePerNight: 380,
    description: 'A cozy cabin in the mountains of Nimba County. Breathtaking views and fresh mountain air.',
    longStay: true,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 4,
    amenities: ['Mountain View', 'WiFi', 'Kitchen', 'Indoor Fireplace'],
    rating: 4.9,
    reviewCount: 68,
    viewCount: 1150,
    images: [findImage('prop14-1'), findImage('prop14-2')],
    owner: { id: users[1].id, name: users[1].name, avatar: users[1].avatar },
    propertyType: 'House',
    petFriendly: false,
    status: 'pending',
  },
  {
    id: 'prop-15',
    name: 'Fish Town Family Bungalow',
    location: 'Fish Town, Liberia',
    pricePerNight: 300,
    description: 'A comfortable bungalow perfect for families visiting River Gee county. Safe and quiet area.',
    longStay: true,
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    amenities: ['WiFi', 'Kitchen', 'Free Parking', 'Air Conditioning'],
    rating: 4.5,
    reviewCount: 42,
    viewCount: 800,
    images: [findImage('prop15-1'), findImage('prop15-2')],
    owner: { id: users[2].id, name: users[2].name, avatar: users[2].avatar },
    propertyType: 'House',
    petFriendly: true,
    status: 'approved',
  },
  {
    id: 'prop-16',
    name: 'Barclayville Seaside Apartment',
    location: 'Barclayville, Liberia',
    pricePerNight: 420,
    weekendPrice: 480,
    description: 'Modern apartment with stunning views of the Atlantic Ocean. Enjoy the sea breeze from your private balcony.',
    longStay: false,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ['Ocean View', 'WiFi', 'Kitchen', 'Air Conditioning', 'Balcony'],
    rating: 4.8,
    reviewCount: 75,
    viewCount: 1400,
    images: [findImage('prop16-1'), findImage('prop16-2')],
    owner: { id: users[3].id, name: users[3].name, avatar: users[3].avatar },
    propertyType: 'Apartment',
    petFriendly: false,
    status: 'approved',
  },
  {
    id: 'prop-17',
    name: 'Bensonville Country Home',
    location: 'Bensonville, Liberia',
    pricePerNight: 330,
    description: 'A spacious and elegant country home with a large garden, perfect for relaxing stays away from the city buzz.',
    longStay: true,
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 8,
    amenities: ['Garden', 'WiFi', 'Kitchen', 'Free Parking', 'Air Conditioning'],
    rating: 4.7,
    reviewCount: 58,
    viewCount: 990,
    images: [findImage('prop17-1'), findImage('prop17-2')],
    owner: { id: users[0].id, name: users[0].name, avatar: users[0].avatar },
    propertyType: 'House',
    petFriendly: true,
    status: 'approved',
  },
  {
    id: 'prop-18',
    name: 'Cestos City Riverfront Condo',
    location: 'Cestos City, Liberia',
    pricePerNight: 290,
    description: 'A modern condo offering beautiful views of the Cestos River. Features contemporary design and a shared community pool.',
    longStay: false,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 4,
    amenities: ['River View', 'WiFi', 'Kitchen', 'Air Conditioning', 'Shared Pool'],
    rating: 4.6,
    reviewCount: 63,
    viewCount: 1210,
    images: [findImage('prop18-1'), findImage('prop18-2')],
    owner: { id: users[1].id, name: users[1].name, avatar: users[1].avatar },
    propertyType: 'Condo',
    petFriendly: false,
    status: 'pending',
  },
  {
    id: 'prop-19',
    name: 'Roberts-field Airport Hotel Suite',
    location: 'Harbel, Liberia',
    pricePerNight: 550,
    description: 'A luxurious suite located minutes from Roberts International Airport. Perfect for business travelers needing convenience and comfort.',
    longStay: false,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ['WiFi', 'Air Conditioning', 'Room Service', 'Airport Shuttle'],
    rating: 4.9,
    reviewCount: 110,
    viewCount: 2100,
    images: [findImage('prop19-1'), findImage('prop19-2')],
    owner: { id: users[2].id, name: users[2].name, avatar: users[2].avatar },
    propertyType: 'Apartment',
    petFriendly: false,
    status: 'approved',
  },
  {
    id: 'prop-20',
    name: 'Monrovia Central Loft',
    location: 'Monrovia, Liberia',
    pricePerNight: 480,
    description: 'A stylish industrial loft in the heart of Monrovia. High ceilings, open-plan living, and close to all major downtown attractions.',
    longStay: false,
    bedrooms: 1,
    bathrooms: 2,
    maxGuests: 3,
    amenities: ['WiFi', 'Kitchen', 'Air Conditioning', 'City View'],
    rating: 4.8,
    reviewCount: 95,
    viewCount: 1800,
    images: [findImage('prop20-1'), findImage('prop20-2')],
    owner: { id: users[3].id, name: users[3].name, avatar: users[3].avatar },
    propertyType: 'Apartment',
    petFriendly: true,
    status: 'approved',
  }
];

export const reviews: Review[] = [
    {
        id: 'rev-1',
        propertyId: 'prop-1',
        user: users[1],
        rating: 5,
        comment: "Absolutely stunning villa! The views were even better than the pictures. Everything was clean and the host was very responsive. Highly recommend!",
        createdAt: "2023-10-20T14:48:00.000Z",
        cleanliness: 5,
        communication: 5,
        checkIn: 5,
        accuracy: 5,
        location: 5,
        value: 5,
    },
    {
        id: 'rev-2',
        propertyId: 'prop-1',
        user: users[2],
        rating: 4,
        comment: "Great location and beautiful house. We had a minor issue with the pool heater but the owner fixed it quickly. Overall, a fantastic stay.",
        createdAt: "2023-09-15T10:30:00.000Z",
        cleanliness: 4,
        communication: 5,
        checkIn: 4,
        accuracy: 5,
        location: 5,
        value: 4,
    },
    {
        id: 'rev-3',
        propertyId: 'prop-2',
        user: users[3],
        rating: 5,
        comment: "The apartment was perfect for our city trip. It's small but has everything you need and the location is unbeatable. We would definitely stay here again.",
        createdAt: "2023-11-05T18:00:00.000Z",
        cleanliness: 5,
        communication: 5,
        checkIn: 5,
        accuracy: 5,
        location: 5,
        value: 5,
    }
];

export const bookings: Booking[] = [
    {
        id: 'book-1',
        userId: 'user-4',
        propertyId: 'prop-1',
        checkInDate: new Date('2024-08-01'),
        checkOutDate: new Date('2024-08-10'),
        totalPrice: 8500,
        guests: 4,
        createdAt: new Date(),
        propertyName: 'Modern Villa with Ocean View',
        propertyImage: 'https://images.unsplash.com/photo-1599777560450-e462cffc5368?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxtb2Rlcm4lMjB2aWxsYXxlbnwwfHx8fDE3Njc3MDYwNzR8MA&ixlib=rb-4.1.0&q=80&w=1080',
        propertyLocation: 'Monrovia, Liberia',
    },
    {
        id: 'book-2',
        userId: 'user-4',
        propertyId: 'prop-3',
        checkInDate: new Date('2024-09-15'),
        checkOutDate: new Date('2024-09-20'),
        totalPrice: 2000,
        guests: 2,
        createdAt: new Date(),
        propertyName: 'Spacious Suburban Family Home',
        propertyImage: 'https://images.unsplash.com/photo-1625603736199-775425d2890a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxzdWJ1cmJhbiUyMGhvdXNlfGVufDB8fHx8MTc2NzY2Nzg1Mnww&ixlib=rb-4.1.0&q=80&w=1080',
        propertyLocation: 'Ganta, Liberia',
    }
];

export const amenities: string[] = [
    'Private Pool',
    'WiFi',
    'Kitchen',
    'Air Conditioning',
    'Free Parking',
    'Gym',
    'Hot Tub',
    'Elevator',
    'Backyard',
    'Grill',
    'Rooftop Terrace',
    'Beach Access',
    'Indoor Fireplace',
    'Garden',
    'City View',
    'Ocean View',
];
